# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
arb-dir: lib/core/l10n 
nullable-getter: false 
synthetic-package: false
output-dir: lib/gen/i18n
untranslated-messages-file: desiredFileName.txt